FROM node:24-bookworm-slim AS builder
WORKDIR /frontend

COPY frontend/package*.json ./
RUN npm ci --only=production

COPY frontend/. ./

RUN npm run build

FROM nginx:1.27-alpine AS prod
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /frontend/dist .

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
