services:

  postgres:
    container_name: casino-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino
      POSTGRES_DB: casino
    ports:
      - 5432:5432
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

volumes:
  postgres_data_container: