ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl ca-certificates python3 build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /backend

COPY package*.json ./
RUN npm install
COPY . .

RUN npx prisma generate --schema=backend/prisma/schema.prisma

RUN chown -R node:node /backend
USER node

ENV NODE_ENV=development \
    PORT=3000 \
    CHOKIDAR_USEPOLLING=1 \
    WATCHPACK_POLLING=true

EXPOSE 3000 9229

CMD ["sh","-c","npx prisma migrate deploy && npm run start:dev"]